# Disable DNS routing
port=0

# Enable DHCP logging
log-dhcp

dhcp-range=192.168.50.0,proxy
dhcp-boot=netboot.xyz.kpxe,,192.168.50.233

# PXE Menu options
pxe-service=x86PC,"Boot to netboot.xyz (BIOS)",netboot.xyz.kpxe
pxe-service=X86-64_EFI,"Boot to netboot.xyz (UEFI)",netboot.xyz.efi
